name:                servant-ts
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/smaccoun/servant-ts#readme
license:             BSD3
author:              Steven MacCoun
maintainer:          theraccoun@gmail.com
copyright:           2018 Steven MacCoun
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson-generic-ts
  - servant
  - servant-foreign
  - text
  - lens
  - prettyprinter

executables:
  servant-ts-mk-docs:
    main: Main.hs
    dependencies:
      - dhall
    source-dirs:
      - docs
      - src
      - mock


library:
  source-dirs: src

tests:
  servant-ts-test:
    main:               Main.hs
    source-dirs:
      - test
      - src
      - mock
    dependencies:
      - hspec

data-dir:
  mock

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- MultiParamTypeClasses
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances


